name: "Check message format"
description: "Commit message should start with #"
inputs:
  message:
    description: "Body of the commit message"
    required: true
runs: 
  using: node12
  main: index.js