name: "Check message format"
description: "Commit message should start with #"
inputs:
  pull_info:
    description: "PR message"
    required: true
outputs:
  result:
    description: "Result of the message validation"
runs: 
  using: node16
  main: index.js
