name: "Check message format"
description: "Commit message should start with #"
inputs:
  push_message:
    description: "Body of the commit message"
    required: flase
  pull_message:
    description: "Body of the commit message"
    required: flase
runs: 
  using: node12
  main: index.js
