name: "Check message format"
description: "Commit message should start with #"
#This action is expecting one input - last commit message 
inputs:
  message:
    description: "Last commit message of the PR"
    required: true
outputs:
  result:
    description: "Result of the message validation"
runs: 
  using: node16
  main: index.js
